SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Books';
SELECT * FROM dbo.Categories;
SELECT * FROM [dbo].__EFMigrationsHistory;

